M0-AntiAnvilRename:
  RenameBlocked: '&4You cannot rename items.'
  CloseOnAttempt: true
  EnableWhitelist: false
  AllowedItems:
    - 'DIAMOND_SWORD'
  EnableBlacklist: false
  DeniedItems:
    - 'TRIPWIRE_HOOK'
  DenyWhileHolding:
    Items:
      - 'DIAMOND_SWORD'
    Commands:
      - '/rename'
    Message: '&4You cannot use this command while holding this item'