name: M0-AntiAnvilRename
main: me.M0dii.AntiAnvilRename.Main
description: M0-AntiAnvilRename
version: 1.4
api-version: 1.16
author: M0dii
permissions:
  m0antianvilrename.bypass:
    description: Bypass the restriction.
    default: op